name: upstage-frontend-dev
services:
  upstage_frontend_dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: upstage/frontend:local
    container_name: upstage_frontend_dev
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    volumes:
      - .:/app
      - /frontend_app_dev/dist:/app/dist
    working_dir: /app
    command: >
      /bin/sh -c "
      rm -rf /app/.env &&
      cat /app/dist/.env > /app/.env &&
      pnpm install --frozen-lockfile &&
      pnpm build:dev &&
      tail -f /dev/null
      "
