name: upstage-frontend-prod
services:
  upstage_frontend_prod:
    image: node:22-bookworm
    container_name: upstage_frontend
    volumes:
      - .:/app
      - /frontend_app/dist:/app/dist
    working_dir: /app
    command: >
      /bin/sh -c "
      rm -rf /app/.env &&
      cat /app/dist/.env > /app/.env &&
      corepack enable &&
      corepack prepare pnpm@10.7.1 --activate &&
      pnpm install --frozen-lockfile &&
      pnpm build &&
      tail -f /dev/null
      "
